### ISSUE TITLE
Theme is crashing - "Cannot find module tinycolor2"

### ISSUE THREAD

**Issue by KacasPiesel** [atom-material/atom-material-ui#319]
I am just starting Atom and... I see a beautiful crash.

It happens on my Windows 10 and Debian 8

**Reproduction Steps:**

1. Install Atom
2. Download and set as default themes: atom-material-ui & atom-material-syntax
3. Close and open Atom.

**Screenshots and GIFs**

[Screenshot](http://screenshot.sh/owpBxe99J3Q5m)

**Atom version:** 1.9.8/1.9.9
**OS and version:** Windows 10/Debian 8 (stable/jessie)

**Installed packages:**

```
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)
```

**Error details:**

```
Error: Cannot find module 'tinycolor2'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Mikolaj/.atom/packages/atom-material-ui/lib/color-settings.js:5:53)
    at Module._compile (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/Mikolaj/.atom/packages/atom-material-ui/lib/main.js:6:34)
    at Module._compile (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at ThemePackage.module.exports.Package.requireMainModule (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:715:27)
    at ThemePackage.module.exports.Package.activateNow (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:173:16)
    at C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:92:15)
    at C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\theme-manager.js:332:52
    at Config.module.exports.Config.observeKeyPath (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:612:7)
    at Config.module.exports.Config.observe (C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:141:21)
    at C:\Users\Mikolaj\AppData\Local\atom\app-1.9.9\resources\app.asar\src\theme-manager.js:322:31

```

**Additional information:**

* Problem happen in an older version of Atom.
* Problem can be reliably reproduced, doesn't happen randomly.

**Comment by silvestreh** [comment]
That's odd. Somehow APM failed to install dependencies. 

Open a terminal and do...

```shell
cd ~/.atom/packages/atom-material-ui/
npm install
```

**Comment by silvestreh** [comment]
Also… how did you install the theme? Sounds like a bug in APM.

**Comment by KacasPiesel** [comment]
Just downloaded in settings of Atom.

**Comment by KacasPiesel** [comment]
I just updated theme and it's working well on Windows. Not tested on Linux.

**Comment by silvestreh** [comment]
This wasn't an issue with the theme. It was a problem with APM, Atom's package manager. It somehow failed to install the dependencies.
