### ISSUE TITLE
Uncaught Error: Cannot find module 'tinycolor2'

### ISSUE THREAD

**Issue by lfkid** [atom-material/atom-material-ui#358]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package 1.3.9

### Stack Trace

Uncaught Error: Cannot find module 'tinycolor2'

```
At module.js:457

Error: Cannot find module 'tinycolor2'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-material-ui/lib/color-settings.js:5:53)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-material-ui/lib/main.js:6:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at ThemePackage.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at ThemePackage.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:51:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at PackageCard.module.exports.PackageCard.initialize (/app.asar/node_modules/settings-view/lib/package-card.js:243:19)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
```

### Commands

```
     -0:21.8.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 1.3.9 
```

**Comment by silvestreh** [comment]
Hey there! Did you install the theme within Atom? The solution is pretty simple, you should open a terminal emulator and…

```shell
cd ~/.atom/packages/atom-material-ui/
apm install
```

For some reason APM didn't install the theme's dependencies. You could also try uninstalling and reinstalling from within Atom's settings.
