### ISSUE TITLE
Failed to activate the atom-material-ui package

### ISSUE THREAD

**Issue by carrodher** [atom-material/atom-material-ui#381]
Following this issue https://github.com/atom-material/atom-material-ui/issues/376 and after trying the development branch (2.0) I obtain this issue.

**Atom**: 1.17.0-beta2 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package 1.3.9

### Stack Trace

Failed to activate the atom-material-ui package

```
At Cannot find module 'tinycolor2'

Error: Cannot find module 'tinycolor2'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Applications/Atom%20Beta.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-material-ui/lib/colors/index.js:3:19)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom%20Beta.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-material-ui/lib/main.js:5:57)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom%20Beta.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:73:1)
    at ThemePackage.module.exports.Package.requireMainModule (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:887:1)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:242:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/theme-package.js:59:1
    at ThemePackage.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/theme-package.js:55:1
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/theme-package.js:51:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/theme-manager.js:353:1
```

### Commands

```
     -0:13.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-clock 0.1.7 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
docblockr 0.9.4 
file-icons 2.1.3 
goto-definition 1.3.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-docker 1.1.7 
language-latex 1.0.0 
language-log 1.8.0 
language-tcl 0.1.2 
latex 0.43.0 
linter 2.1.4 
linter-chktex 1.3.0 
linter-docker 0.2.0 
linter-eslint 8.1.6 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-js-yaml 1.2.7 
linter-jsonlint 1.3.0 
linter-shellcheck 1.4.4 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
minimap 4.27.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
multi-cursor 2.1.5 
pretty-json 1.6.3 
tree-view-git-status 1.3.1 
```

**Comment by silvestreh** [comment]
This keeps popping every once in a while. For some obscure (at least to me) reason, APM will fail to install the theme's dependencies.

You can either…
1. Install the missing dependencies manually
    - `cd ~/.atom/packages/atom-material-ui && npm install`
2. Uninstall and install the theme from within Atom

Let me know if that works

**Comment by carrodher** [comment]
Yes, it works, thanks. The issue was solved.
