### ISSUE TITLE
Uncaught Error: Cannot find module 'tinycolor2'

### ISSUE THREAD

**Issue by LaMaravish** [atom-material/atom-material-ui#382]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-material-ui](https://github.com/silvestreh/atom-material-ui) package 1.3.9

### Stack Trace

Uncaught Error: Cannot find module 'tinycolor2'

```
At module.js:457

Error: Cannot find module 'tinycolor2'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-material-ui-master/lib/color-settings.js:5:53)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-material-ui-master/lib/main.js:6:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at ThemePackage.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at ThemePackage.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:785:34)
    at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:430:16)
    at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:422:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:84:10)
    at InstallPanel.getPackageCardView (/app.asar/node_modules/settings-view/lib/install-panel.js:385:14)
    at InstallPanel.addPackageViews (/app.asar/node_modules/settings-view/lib/install-panel.js:371:49)
    at /app.asar/node_modules/settings-view/lib/install-panel.js:441:20
    at /app.asar/node_modules/settings-view/lib/atom-io-client.js:60:20
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/app.asar/node_modules/settings-view/lib/atom-io-client.js:150:16)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/app.asar/node_modules/settings-view/lib/atom-io-client.js:57:19)
    at InstallPanel.loadFeaturedPackages (/app.asar/node_modules/settings-view/lib/install-panel.js:435:21)
    at /app.asar/node_modules/settings-view/lib/install-panel.js:108:10)
    at /app.asar/node_modules/settings-view/lib/settings-view.js:225:16
    at SettingsView.getOrCreatePanel (/app.asar/node_modules/settings-view/lib/settings-view.js:349:19)
    at SettingsView.showPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:407:24)
    at HTMLDivElement.clickHandler (/app.asar/node_modules/settings-view/lib/settings-view.js:174:18)
```

### Commands

```
     -8:08.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.23 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
change-case 0.6.5 
emmet 2.4.3 
file-icons 2.1.3 
intentions 1.1.2 
linter 2.1.4 
linter-jshint 3.0.3 
linter-ui-default 1.2.3 
minimap 4.27.1 
monokai-seti 0.8.0 
seti-icons 1.4.3 
terminal-plus 0.14.5 
```

**Comment by silvestreh** [comment]
Uninstall and reinstall. Please search through closed issues, this pops up like once a week 😁. For some reason APM doesn't install the package's dependencies.
